unit_price: "vnđ"
books:
  precision_min: 0
  previous_week: 1
  per_page: 18
hot_items:
  limit: 10
percentage: 100
book_title: 70
related_book:
  limit: 3
format_time: "%d-%m-%Y"
textarea:
  number_rows: 7
